CI: use package-ci/mac image instead of buildfarm/mac
Fix the following errors:
```
[12:31:47.729 INF] UPM-CI is not compatible with your installed version of Nodejs (v9.8.0). Please use Nodejs v10 or above.
For more information on how to resolve this error, including in CI: https://github.cds.internal.unity3d.com/unity/upm-ci-utils#upm-ci-is-not-compatible
---------
/usr/local/lib/node_modules/upm-ci-utils/scripts/postinstall.js:9
    throw new Error(`Incompatible Nodejs Version (${process.version})`);
    ^

Error: Incompatible Nodejs Version (v9.8.0)
    at checkEngineVersion (/usr/local/lib/node_modules/upm-ci-utils/scripts/postinstall.js:9:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/upm-ci-utils/scripts/postinstall.js:13:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```